ITUscheduler/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from api.models import MajorCode
from .sitemaps import StaticViewSitemap, IndexViewSitemap
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/reset-password', auth_views.PasswordResetView.as_view(), name="password-reset"),
    path('accounts/reset-password-done', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('accounts/reset-password-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('accounts/reset-password-complete', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('sitemap.xml', sitemap, {'sitemaps': {
            'home': IndexViewSitemap,
            'pages': StaticViewSitemap,
            'courses': GenericSitemap({"queryset": MajorCode.objects.all()}, priority=0.7)
        }
    }, name='django.contrib.sitemaps.views.sitemap'),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('', include('scheduler.urls')),
    path('api/', include('api.urls')),
    path('rest-api/', include('api.rest_api.urls', namespace='course_api')),
    path('schedules-rest-api/', include('scheduler.rest_api.urls', namespace='rest_api_scheduler')),
    path('info/', include('blog.urls', namespace='info')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/rest_api/urls.py
from .views import CourseListAPIView, CourseDetailAPIView, MajorCodeListAPIView
from django.urls import path

app_name = 'course_api'

urlpatterns = [
    path('courses/<slug:major_code>', CourseListAPIView.as_view(), name='list_api'),
    path('detail/', CourseDetailAPIView.as_view(), name='list_detail'),
    path('major-codes', MajorCodeListAPIView.as_view(), name='major_code_list_api'),
]

api/urls.py
from django.urls import path
from api import views

urlpatterns = [
    path('refresh/courses', views.RefreshCoursesView.as_view(), name="refresh_courses"),
    path('flush', views.FlushView.as_view(), name="flush"),
    path('db/refresh/major_codes', views.db_refresh_major_codes, name="db_refresh_major_codes"),
    path('db/refresh/courses', views.db_refresh_courses, name="db_refresh_courses"),
    path('db/flush', views.db_flush, name="db_flush")
]

scheduler/rest_api/urls.py
from django.urls import path
from .views import ScheduleListAPIView, ScheduleDetailAPIView, course_remove, course_replace, add_to_schedule, read_notification

app_name = 'rest_api_scheduler'

urlpatterns = [
    path('list/', ScheduleListAPIView.as_view(), name='api_schedule_list'),
    path('detail/<int:pk>', ScheduleDetailAPIView.as_view(), name='api_schedule_detail'),
    path('course-remove/', course_remove, name='course_remove'),
    path('course-replace/', course_replace, name='course_replace'),
    path('add_to_schedule/<int:id>', add_to_schedule, name='add_to_schedule'),
    path('read-notification/', read_notification, name='read_notification'),
]

scheduler/urls.py
from django.urls import path
from scheduler import views

urlpatterns = [
    # path('', views.shutdown, name="shutdown"),
    path('', views.IndexView.as_view(), name="index"),
    path('schedule/<int:pk>', views.IndexView.as_view(), name="schedule"),
    path('share/<str:username>/', views.ScheduleView.as_view(), name="share"),
    path('signup', views.RegistrationView.as_view(), name="signup"),
    path('courses', views.CoursesView.as_view(), name="courses"),
    path('contact/', views.contact, name="contact"),
    path('my-courses/remove', views.remove_my_courses, name="remove_my_courses"),
    path('schedule/addCourse', views.add_course, name="add_course"),
    path('schedule/select', views.select_schedule, name="select_schedule"),
    path('schedule/delete', views.delete_schedule, name="delete_schedule"),
    path('schedule', views.schedule_export, name="schedule_export"),
    path('schedule.png', views.ScheduleExportView.as_view(), name="schedule_png"),
    path('schedule.pdf', views.ScheduleExportView.as_view(), name="schedule_pdf"),
    path('privacy-policy', views.privacy_policy, name="privacy_policy"),
    path('sis/', views.sis, name="sis"),
    path('ads.txt/', views.ads, name="ads"),
    path('robots.txt/', views.robots, name="robots")
    #path('schedule/removeCourse/<int:pk>/<int:pk>', views.remove_course, name='remove_course'),
    #path('schedule/replaceCourse', views.replace_course, name='replace_course'),
]

scheduler/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from api.models import Course, MajorCode, Semester


def get_semester():
    try:
        semester = Semester.objects.current()
        return semester.pk
    except Exception:
        return 0


class ExtendedUser(AbstractUser):
    courses = models.ManyToManyField(Course, blank=True)
    my_major_code = models.ForeignKey(MajorCode, blank=True, null=True, on_delete=models.SET_NULL)
    my_semester = models.ForeignKey(Semester, default=get_semester(), on_delete=models.SET_DEFAULT)
    my_schedule = models.ForeignKey("Schedule", blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.username)


class Schedule(models.Model):
    user = models.ForeignKey(ExtendedUser, null=True, on_delete=models.CASCADE)
    courses = models.ManyToManyField(Course)

    class Meta:
        get_latest_by = 'id'

    def __str__(self):
        if self.user:
            for index, schedule in enumerate(self.user.schedule_set.all()):
                if schedule.id == self.id:
                    return str(self.user) + " #" + str(index + 1)
        else:
            return str(self.user) + " #" + str(self.id)

    def get_absolute_url(self):
        return reverse("schedule", kwargs={"pk": self.id})


class Notification(models.Model):
    user = models.ForeignKey(ExtendedUser, on_delete=models.CASCADE)
    msg = models.CharField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return str(self.msg)

scheduler/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from scheduler.models import Schedule


class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(
        required=True,
        widget=forms.Textarea
    )


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(label='Your ITU email address')

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email')

    def clean_email(self):
        data = self.cleaned_data['email']
        if '@itu.edu.tr' != data[-11:]:
            raise forms.ValidationError('This is not a valid ITU email address!')
        return data


class ScheduleForm(forms.ModelForm):
    def __init__(self, courses=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if courses is not None:
            self.fields["courses"].queryset = courses

    class Meta:
        model = Schedule
        exclude = []
        widgets = {
            "user": forms.HiddenInput()
        }

scheduler/rest_api/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView
from rest_framework.response import Response
from rest_framework.status import HTTP_401_UNAUTHORIZED
from rest_framework.decorators import api_view, permission_classes, authentication_classes
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated

from django.shortcuts import get_object_or_404
from django.contrib import messages

from .serializers import ScheduleSerializer
from scheduler.views import is_available
from api.rest_api.serializers import CourseSerializer, LectureSerializer, PrerequisiteSerializer
from api.models import Course
from scheduler.models import Schedule, Notification


class ScheduleListAPIView(ListAPIView):
    serializer_class = ScheduleSerializer
    queryset = Schedule.objects.all()

    def list(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        queryset = queryset.filter(user=request.user)

        # serializer = self.get_serializer(queryset, many=True)

        data = [(self.get_serializer(query).data, query) for query in queryset]
        response_data = []

        for serializer, query in data:
            serializer['courses'] = CourseSerializer(query.courses.all(), many=True).data
            response_data.append(serializer)

        for data in response_data:
            for course in data['courses']:
                query = Course.objects.get(crn=course['crn'])
                course['lectures'] = LectureSerializer(query.lecture_set.all(), many=True).data
                course['prerequisites'] = PrerequisiteSerializer(query.prerequisites.all(), many=True).data

        return Response(response_data)


class ScheduleDetailAPIView(RetrieveAPIView):
    serializer_class = ScheduleSerializer
    queryset = Schedule.objects.all()

    def retrieve(self, request, *args, **kwargs):
        # if request.user == self.get_object().user:
            instance = self.get_object()
            serializer = self.get_serializer(instance).data
            serializer['courses'] = CourseSerializer(instance.courses.all(), many=True).data
            for data in serializer['courses']:
                query = Course.objects.get(crn=data['crn'])

                available, _ = is_available(instance.courses.all(), query)

                if not available:
                    data['overlaps'] = True
                else:
                    data['overlaps'] = False

                data['lectures'] = LectureSerializer(query.lecture_set.all(), many=True).data
                data['prerequisites'] = PrerequisiteSerializer(query.prerequisites.all(), many=True).data

            return Response(serializer)

        # return Response({'Unauthorized attempt'}, status=HTTP_401_UNAUTHORIZED)


@api_view(['POST'])
@permission_classes((IsAuthenticated, ))
@authentication_classes((SessionAuthentication, ))
def course_remove(request):
    crn = int(request.data['crn'])
    schedule_id = int(request.data['schedule_id'])
    user = request.user

    schedule = get_object_or_404(Schedule, id=schedule_id)
    course = get_object_or_404(Course, crn=crn)
    if schedule.user != user and course not in schedule:
        return Response({'error': 'unauthorized attempt.'}, status=HTTP_401_UNAUTHORIZED)

    schedule.courses.remove(course)

    if len(schedule.courses.all()) == 0:
        schedule.delete()

    return Response({'success': 'Successfuly removed course {}'.format(course.crn)})


@api_view(['POST'])
@permission_classes((IsAuthenticated, ))
@authentication_classes((SessionAuthentication, ))
def course_replace(request):
    old_crn = int(request.data['old_crn'])
    new_crn = int(request.data['new_crn'])
    schedule_id = int(request.data['schedule_id'])
    user = request.user

    schedule = get_object_or_404(Schedule, id=schedule_id)
    old_course = get_object_or_404(Course, crn=old_crn)
    new_course = get_object_or_404(Course, crn=new_crn)

    if schedule.user != user and old_course not in schedule and new_course in schedule:
        return Response({'error': 'Unauthorized attempt.'}, status=HTTP_401_UNAUTHORIZED)

    schedule.courses.remove(old_course)
    schedule.courses.add(new_course)

    return Response({'success': 'Replaced {} with {}'.format(old_crn, new_crn)})


@api_view(['POST'])
@permission_classes((IsAuthenticated, ))
@authentication_classes((SessionAuthentication, ))
def add_to_schedule(request, id):
    try:
        schedule = Schedule.objects.get(id=id)
        if schedule.user == request.user:
            data = [int(crn) for crn in dict(request.data)['courses']]
            courses = [Course.objects.get(crn=crn) for crn in data]

            for course in courses:
                if course not in schedule.courses.all():
                    schedule.courses.add(course)
                    if not course.is_full():
                        available, _course = is_available(schedule.courses.all(), course)

                        if not available:
                            messages.warning(request._request, "Course #{} overlaps #{}. Your schedule is created anyway but please mind this.".format(course.crn, _course.crn, course.crn))
                    else:
                        msg = "Course {} is full, your schedule is created anyway but please mind this.".format(
                            course.crn)

                        notification = Notification()
                        notification.user = request.user
                        notification.msg = msg
                        notification.save()

            return Response({'success': 'attempt is accomplished'})
        else:
            raise Exception("Unauthorized attempt")
    except Exception as error:
        return Response({'error': error})


@api_view(["POST"])
@permission_classes((IsAuthenticated, ))
@authentication_classes((SessionAuthentication, ))
def read_notification(request):
    try:
        notification = Notification.objects.get(id=request.data['id'])
        if notification.user != request.user:
            raise Exception("Not authorized!")

        notification.read = True
        notification.save()

        return Response({'success': 'attempt is accomplished'})

    except Exception as error:
        return Response({'error': error})

scheduler/templates/base.html
{% load static gravatar %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-63317374-5"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-63317374-5');
    </script>
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<script>
  		(adsbygoogle = window.adsbygoogle || []).push({
    		google_ad_client: "ca-pub-9144734939845709",
    		enable_page_level_ads: true
  		});
	</script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <title>{% block title %}ITU Scheduler{% endblock %}</title>
    <meta property="og:title" content="ITU Scheduler">
    <meta property="og:description" content="With ITU Scheduler you can browse up-to-date ITU courses and create possible course schedules easily without the need of another resource.">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://ituscheduler.com/">
    <meta property="og:image" content="https://ituscheduler.com/static/icons/android-chrome-512x512.png">
    <meta property="og:image:height" content="512">
    <meta property="og:image:width" content="512">
    {% include 'meta/meta.html' %}
    {% load static %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "icons/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "icons/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "icons/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "icons/manifest.json" %}">
    <link rel="mask-icon" href="{% static "icons/safari-pinned-tab.svg" %}" color="#063d4d">
    <link rel="shortcut icon" href="{% static "icons/favicon.ico" %}">
    <meta name="apple-mobile-web-app-title" content="ITUscheduler">
    <meta name="application-name" content="ITUscheduler">
    <meta name="msapplication-config" content="{% static "icons/browserconfig.xml" %}">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/font-awesome.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-social.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="{% static "js/jquery-3.2.1.min.js" %}"></script>
</head>
<body>
    <div class="content">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">
                        <img src="{% static "icons/bee-transparent-white.png" %}" height="44px" style="display: inline-block; position: absolute; top: 8px">
                        <span style="padding-left: 50px"><strong>ITUscheduler</strong></span>
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        {% url "index" as index_url %}
                        <li {% if request.path == index_url %}class="active"{% endif %}><a href="{{ index_url }}">Home </a></li>
                        {% url "courses" as courses_url %}
                        <li {% if "courses" in request.path %}class="active"{% endif %}><a href="{{ courses_url }}">Courses </a></li>
                        {% url "contact" as contact_url %}
                        <li {% if "contact" in request.path %}class="active"{% endif %}><a href="{{ contact_url }}">Contact </a></li>
                        {% url "info:index" as info_url %}
                        <li {% if "info" in request.path %}class="active"{% endif %}><a href="{{ info_url }}">Info </a></li>
{#                        <li class="dropdown">#}
{#                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">API <span class="caret"></span></a>#}
{#                            <ul class="dropdown-menu" role="menu">#}
{#                                <li><a href="{% url "course_api:major_code_list_api"%}">Major Codes</a></li>#}
{#                                <li><a href="{% url "course_api:list_api" major_code="BLG"%}">Courses</a></li>#}
{#                            </ul>#}
{#                        </li>#}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Rehberler <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="http://web.itu.edu.tr/durgunor/ders.htm" target="_blank">Ders Seçim Rehberi</a></li>
                                <li><a href="http://web.itu.edu.tr/durgunor/itusch.htm" target="_blank">ITUscheduler Nasıl Kullanılır?</a></li>
                                <li><a href="http://web.itu.edu.tr/durgunor/crn.html" target="_blank">Fill CRN Test</a></li>
                            </ul>
                        </li>
                        <li><a href="http://notkutusu.com" target="_blank">Not Kutusu</a></li>
                        <li><a href="https://ebrawler.com" target="_blank">eBrawler</a></li>
                        {% if request.user.is_authenticated %}
                            {% if request.user.is_superuser %}
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Database <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="{% url "db_refresh_major_codes" %}">Refresh Major Codes</a></li>
                                        <li><a href="{% url "refresh_courses" %}">Refresh Courses</a></li>
                                        <li><a href="{% url "flush" %}">Flush</a></li>
                                    </ul>
                                </li>
                            {% endif %}
                            <li><a href="/{% if request.user.is_superuser %}admin{% endif %}">{{request.user.username}}<span style="margin-left: 15px;">{% gravatar request.user.email 18 %}</span></a></li>
                            {% url "logout" as logout_url %}
                            <li {% if request.path == logout_url %}class="active"{% endif %}><a href="{% url "logout" %}">Logout </a></li>
                        {% else %}
                            {% url "signup" as signup_url %}
                            <li {% if request.path == signup_url %}class="active"{% endif %}><a href="{% url "signup" %}">Sign Up </a></li>
                            {% url "login" as login_url %}
                            <li {% if request.path == login_url %}class="active"{% endif %}><a href="{% url "login" %}">Login </a></li>
                        {% endif %}
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <script src="{% static "js/tether.min.js" %}"></script>
        <script src="{% static "js/bootstrap.min.js" %}"></script>
        <script src="{% static "js/main.js" %}"></script>
        {% block body %}{% endblock %}
    </div>
    <footer class="navbar navbar-default footer">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="//github.com/ITUscheduler/ITUscheduler" target="_blank"><span class="copyleft">&copy;</span> Copyleft 2018 | ITUscheduler</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="http://dorukgezici.com" target="_blank">Doruk Gezici</a></li>
                <li><a href="//github.com/mehmetaltuner" target="_blank">Mehmet Altuner</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

scheduler/templates/contact.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}Contact | ITU Scheduler{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Contact <small style="margin-left: 20px;"><a href="mailto:info@ituscheduler.com">info@ituscheduler.com</a></small></h1>
                <h4>You can contact us regarding bugs, feature requests, etc...</h4><br>
                <form role="form" action="" method="post">
                    {% csrf_token %}
                    {{ form|bootstrap }}
                    <button class="btn btn-primary" type="submit">Submit</button>
                </form>
            </div>
        </div>
        <br>
    </div>
    <script>
        $(document).ready(function() {
            {% if successful %}
                alert("Your message is sent!");
            {% endif %}
        });
    </script>
{% endblock %}

scheduler/templates/schedule_generator.html
{% extends "base.html" %}

{% block title %}Courses | ITU Scheduler{% endblock %}

{% block body %}
    <div class="container">
        <p>{{ tree }}</p>
        <hr>
        <p>{{ matrix }}</p>
        <hr>
        {% for course in courses %}
            <p>{{ course }}</p>
        {% endfor %}
    </div>
{% endblock %}

scheduler/templates/share.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}{{ object }} | ITU Scheduler{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h2 class="panel-title">
                            <div class="row">
                                <div class="col-md-6">
                                    {% if has_schedule %}
                                        {{ object.my_schedule }}
                                        <button style="margin-left: 40px;" class="btn btn-default btn-xs" onclick="copyStringToClipboard(window.location.href);">Copy share link!</button>
                                    {% else %}
                                        {{ object }} has no schedules!
                                    {% endif %}
                                </div>
                                <div class="col-md-6">
                                    <span class="pull-right">{{ object.my_schedule.courses.first.semester.get_name_display }}</span>
                                </div>
                            </div>
                        </h2>
                    </div>
                    <div class="panel-body">
                        {% if has_schedule %}
                            <div class="row">
                                <div class="col-md-12" style="margin-top: 10px;">
                                    <ul class="list-group">
                                        {% for course in object.my_schedule.courses.all %}
                                            <li class="list-group-item">{{ course }}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        {% endif %}
                        <div style="margin-top: 10px;" class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th>Hours</th>
                                    <th>Monday</th>
                                    <th>Tuesday</th>
                                    <th>Wednesday</th>
                                    <th>Thursday</th>
                                    <th>Friday</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for hour in hours %}
                                    <tr id="{{ hour.time|slugify }}">
                                        <th>{{ hour.time }}</th>
                                        <td id="{{ hour.time|slugify }}-{{ 1 }}"></td>
                                        <td id="{{ hour.time|slugify }}-{{ 2 }}"></td>
                                        <td id="{{ hour.time|slugify }}-{{ 3 }}"></td>
                                        <td id="{{ hour.time|slugify }}-{{ 4 }}"></td>
                                        <td id="{{ hour.time|slugify }}-{{ 5 }}"></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            {% if has_schedule %}
                writeLectures();
            {% endif %}
        });

        function copyStringToClipboard(str) {
            var el = document.createElement('textarea');
            el.value = str;
            // Set non-editable to avoid focus and move outside of view
            el.setAttribute('readonly', '');
            el.style = {position: 'absolute', left: '-9999px'};
            document.body.appendChild(el);
            // Select text inside element
            el.select();
            // Copy text to clipboard
            document.execCommand('copy');
            // Remove temporary element
            document.body.removeChild(el);
            alert("Copied share link to clipboard: " + str);
        }

        function idGenerator(start, finish, Ids) {
            var ids = Ids;
            if ((start - 1) === finish) {
                return ids
            } else {
                var id = "#" + start + "-" + (start + 99);
                ids.push(id);
                return idGenerator(start + 100, finish, ids);
            }
        }

        function writeLectures() {
            $.ajax({
                {% if has_schedule %}
                    url: "{% url 'rest_api_scheduler:api_schedule_detail' pk=object.my_schedule_id %}",
                {% else %}
                    url: "#",
                {% endif %}
                success: function(result) {
                    console.log("Lectures writing.");
                    for (var course in result.courses) {
                        for (var lecture in result.courses[course].lectures) {
                            var c_lecture = result.courses[course].lectures[lecture];
                            var c_course = result.courses[course];

                            if (c_lecture.time_start.toString().substring(2) === "00") {
                                c_lecture.time_start = (c_lecture.time_start - 70);
                                c_lecture.time_finish = (c_lecture.time_finish + 70);
                            }

                            var ids = [];
                            var blocks = ((c_lecture.time_finish - c_lecture.time_start) % 99) + 1;

                            if (blocks === 1) {
                                var id = "#" + c_lecture.time_start + "-" + c_lecture.time_finish;
                                ids.push(id);
                            } else {
                                ids = idGenerator(c_lecture.time_start, c_lecture.time_finish, []);
                            }

                            for (var Id in ids) {
                                var id = ids[Id];
                                if (c_lecture.day === "Pazartesi") {
                                    id += "-" + "1"
                                } else if (c_lecture.day === "Salı") {
                                    id += "-" + "2"
                                } else if (c_lecture.day === "Çarşamba") {
                                    id += "-" + "3"
                                } else if (c_lecture.day === "Perşembe") {
                                    id += "-" + "4"
                                } else if (c_lecture.day === "Cuma") {
                                    id += "-" + "5"
                                }

                                if (c_course.overlaps) {
                                    $(id).css({'background-color': '#d9534f', 'color': 'white'});
                                }

                                $(id).html(c_course.title);

                            }
                        }
                    }
                }
            });
        }
    </script>
{% endblock %}