api/urls.py
from django.urls import path
from api import views

urlpatterns = [
    path('refresh/courses', views.RefreshCoursesView.as_view(), name="refresh_courses"),
    path('flush', views.FlushView.as_view(), name="flush"),
    path('db/refresh/major_codes', views.db_refresh_major_codes, name="db_refresh_major_codes"),
    path('db/refresh/courses', views.db_refresh_courses, name="db_refresh_courses"),
    path('db/flush', views.db_flush, name="db_flush")
]

blog/urls.py
from django.urls import path
from .views import PostListView

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='index'),
]

blog/models.py
from django.db import models
from scheduler.models import ExtendedUser


class Post(models.Model):
    author = models.ForeignKey(ExtendedUser, on_delete=models.PROTECT)
    content = models.TextField()
    media = models.ImageField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return str(self.content[:40])

blog/views.py
from django.views.generic import ListView
from django.core.paginator import Paginator
from .models import Post
from api.models import Course, MajorCode, Semester
from scheduler.models import Schedule
from scheduler.models import ExtendedUser


class PostListView(ListView):
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 3
    refresh_paginator = Paginator(MajorCode.objects.all(), 29)

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        courses_count = Course.objects.filter(semester=Semester.objects.current()).count()
        total_schedule_count = Schedule.objects.all().count()
        user_count = ExtendedUser.objects.all().count()

        context["courses_count"] = courses_count
        context["total_schedule_count"] = total_schedule_count
        context["user_count"] = user_count

        refresh_page = self.request.GET.get("refresh_page")
        context["refreshes"] = self.refresh_paginator.get_page(refresh_page)

        return context

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %}Info | ITU Scheduler{% endblock %}

{% block body %}
    <div class="container">
        <div class="row"> <!-- statistics and important info -->
            <div class="col-md-3 col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3>Statistics</h3>
                    </div>
                    <div class="panel-body">
                        <h4>ITUscheduler has</h4>
                        <h4><strong>{{ user_count }}</strong> users</h4>
                        <hr>
                        <h4>Users have created</h4>
                        <h4><strong>{{ total_schedule_count }}</strong> schedules</h4>
                        <hr>
                        <h4>{{ current_semester.get_name_display }}</h4>
                        <h4>has <strong>{{ courses_count }}</strong> courses</h4>
                    </div>
                    <div class="panel-heading">
                        <h3>Latest Refresh</h3>
                    </div>
                    <div class="panel-body">
                        {% for major_code in refreshes %}
                            <p>{{ major_code.code }}: {{ major_code.refreshed }}</p>
                            {% if not forloop.last %}<hr>{% endif %}
                        {% endfor %}
                        <nav aria-label="Latest Refresh Pagination">
                            <ul id="paginator" class="pagination pagination-sm">
                                {% for object in refreshes.paginator.page_range %}
                                    <li class="page-item{% if object == refreshes.number %} active{% endif %}">
                                        <a class="page-link" href="{% url 'blog:index' %}?refresh_page={{ object }}#paginator">{{ object }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="col-md-5 col-xs-12 center">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <div class="row">
                            <h2>Welcome to ITU Scheduler!</h2><hr>
                            <h4 style="line-height: 1.3em;">ITUscheduler is an <a href="//github.com/dorukgezici/ITUscheduler" target="_blank">open-source</a> web application that allows Istanbul Technical University students to browse up-to-date & detailed information about courses and create schedules with ease. It has features like course queries according to days, notifying the user if a course is removed from SIS, exporting the schedule and so on. We also have some features planned like automatic schedule generation, displaying data from previous years, prerequisite checking, etc..</h4>
                        </div>
                        <div class="row">
                            <p style="margin-top: 5px;">Developed by <a href="http://dorukgezici.com" target="_blank">Doruk Gezici</a> & <a href="//github.com/mehmetaltuner" target="_blank">Mehmet Altuner</a></p>
                            <em>We do not gurantee or can be responsible for the accuracy of information found here. If in doubt, please check <a href="http://www.sis.itu.edu.tr" target="_blank">SIS</a>.</em>
                        </div><hr>
                    </div>
                </div>
                <div class="row">
                    {% for post in posts %}
                        <div class="media">
                            <div class="media-body">
                                <h5 class="media-heading">by <strong>{{ post.author }}</strong>, {{ post.date_created|timesince }} ago</h5>
                                <p>{{ post.content|safe }}</p>
                                {% if post.media %}
                                    <img src="{{ post.media.url }}" class="img img-responsive img-rounded">
                                {% endif %}
                                {% if not forloop.last %}
                                    <hr>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4 col-xs-12">
                <a class="twitter-timeline" data-height="2400" href="https://twitter.com/ITUscheduler?ref_src=twsrc%5Etfw">Tweets by ITUscheduler</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
        </div>
        <div class="row">
            <div class="col-md-5 col-xs-12">

            </div>
        </div>
    </div>
{% endblock %}